# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 06:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApuestaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('1', 'Local'), ('x', 'Empate'), ('2', 'Visita')], max_length=2)),
                ('momio_aouesta', models.IntegerField()),
                ('monto_apuesta', models.DecimalField(decimal_places=2, max_digits=11)),
                ('monto_ganar', models.DecimalField(decimal_places=2, max_digits=11)),
                ('estatus', models.CharField(choices=[('abierta', 'Abierta'), ('ganada', 'Ganada'), ('cancelada', 'Cancelada'), ('perdida', 'Perdida')], default='abierta', max_length=8)),
                ('fecha_apuesta', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ApuestaUsuario',
                'verbose_name_plural': 'ApuestaUsuarios',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_corto', models.CharField(max_length=6)),
                ('logo', models.ImageField(blank=True, default='logos/no-logo.jpg', null=True, upload_to='logos/')),
                ('efectividad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.IntegerField()),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='apuestas.Equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='apuestas.Equipo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcador_local', models.IntegerField()),
                ('marcador_visitante', models.IntegerField()),
                ('resultado', models.CharField(choices=[('1', 'Local'), ('x', 'Empate'), ('2', 'Visita')], max_length=50)),
                ('fecha_resultado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ResultadoEvento',
                'verbose_name_plural': 'ResultadoEventos',
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=200, max_digits=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='apuestausuario',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuestas.Evento'),
        ),
        migrations.AddField(
            model_name='apuestausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
