# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apuestas', '0002_auto_20171019_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoevento',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apuestas.Evento'),
        ),
        migrations.AddField(
            model_name='resultadoevento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
