# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0003_auto_20171019_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apuestas.Liga'),
        ),
        migrations.AddField(
            model_name='evento',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apuestas.Torneo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apuestas.Liga'),
        ),
    ]
